version: '3.8'

services:
  mcp-server:
    build: .
    container_name: business-plan-mcp
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - NODE_ENV=production
    restart: unless-stopped